# Generated by Django 5.0.1 on 2024-01-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ratingsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customuser')),
            ],
        ),
    ]
