# Generated by Django 5.0.1 on 2024-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_ratingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsubject',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ratingsubject',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
